runtime: custom
env: flex

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  PORT: "8080"